import { Category } from '../model/category.model';

export const CATEGORIES_MOCK: Category[] = [
  {
    id: '1',
    name: 'Зарплата',
    type: 'income',
    color: '#4CAF50',
    icon: 'salary',
  },
  {
    id: '2',
    name: 'Продукты',
    type: 'expense',
    color: '#FF5735',
    icon: 'cart',
  },
  {
    id: '3',
    name: 'qwertyuio',
    type: 'expense',
    color: '#FF5782',
    icon: 'cart',
  },
  {
    id: '4',
    name: 'asdfghjk',
    type: 'expense',
    color: '#FF5712',
    icon: 'cart',
  },
  {
    id: '5',
    name: 'zxcvbnm',
    type: 'expense',
    color: '#FF5123',
    icon: 'cart',
  },
  {
    id: '6',
    name: 'test ',
    type: 'expense',
    color: '#FF5999',
    icon: 'cart',
  },
  {
    id: '7',
    name: 'test1 ',
    type: 'expense',
    color: '#FF5999',
    icon: 'cart',
  },
  {
    id: '8',
    name: 'test 2',
    type: 'expense',
    color: '#FF5999',
    icon: 'cart',
  },
  {
    id: '9',
    name: 'test 3',
    type: 'expense',
    color: '#FF5999',
    icon: 'cart',
  },
  {
    id: '10',
    name: 'tescfvgbhnt 3',
    type: 'expense',
    color: '#FF5999',
    icon: 'cart',
  },
  {
    id: '11',
    name: 'testdcfvgbhn 4',
    type: 'expense',
    color: '#FF5999',
    icon: 'cart',
  },
  {
    id: '12',
    name: 'test sdfgh5',
    type: 'expense',
    color: '#FF5999',
    icon: 'cart',
  },
  {
    id: '13',
    name: 'test 6',
    type: 'expense',
    color: '#FF5999',
    icon: 'cart',
  },
];
