import { Transaction } from '../model/transaction.model';

export const TRANSACTIONS_MOCK: Transaction[] = [
  {
    id: '1',
    fromAccountName: 'Основной счёт',
    toAccountName: null,
    counterpartyName: 'Пятёрочка',
    categoryName: 'Продукты',
    amount: 500,
    type: 'expense',
    date: '2026-04-04T14:31:00',
    description: 'Покупка продуктов',
    categoryColor: '#FF6B6B',
  },
  {
    id: '2',
    fromAccountName: 'Работа',
    toAccountName: 'Основной счёт',
    counterpartyName: null,
    categoryName: 'Зарплата',
    amount: 30000,
    type: 'income',
    date: '2026-04-01T10:00:00',
    description: 'Зарплата за месяц',
    categoryColor: '#4CAF50',
  },
  {
    id: '3',
    fromAccountName: 'Основной счёт',
    toAccountName: 'Накопительный счёт',
    counterpartyName: null,
    categoryName: 'Переводы',
    amount: 10000,
    type: 'expense',
    date: '2026-04-02T18:20:00',
    description: 'Перевод на накопления',
    categoryColor: '#2196F3',
  },
  {
    id: '4',
    fromAccountName: 'Основной счёт',
    toAccountName: null,
    counterpartyName: 'Starbucks',
    categoryName: 'Кафе',
    amount: 120,
    type: 'expense',
    date: '2026-04-03T09:15:00',
    description: 'Кофе',
    categoryColor: '#795548',
  },
  {
    id: '5',
    fromAccountName: 'Друг',
    toAccountName: 'Основной счёт',
    counterpartyName: null,
    categoryName: 'Переводы',
    amount: 2000,
    type: 'income',
    date: '2026-04-05T20:00:00',
    description: 'Вернул долг',
    categoryColor: '#8BC34A',
  },
];
